sonar.projectKey=jeffreywevans_Telegraphy
sonar.organization=jeffreywevans


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Telegraphy
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\\" by "/" on Windows.
sonar.sources=telegraphy
sonar.tests=tests

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=telegraphy/scripts/cov_init/sitecustomize.py,telegraphy/scripts/run_coverage_workflow.py,telegraphy/story_brief/__main__.py
