[tox]
envlist = py312
skipsdist = True

[testenv]
deps =
    -e .[dev]
changedir = {toxworkdir}
setenv =
    COVERAGE_PROCESS_START = {toxinidir}/tox.ini
    COVERAGE_FILE = {toxworkdir}/.coverage
    TOX_PROJECT_ROOT = {toxinidir}
    PYTHONPATH = {toxinidir}{pathsep}{toxinidir}/commuted_calligraphy/scripts/cov_init
commands =
    python -m commuted_calligraphy.scripts.run_coverage_workflow

[coverage:run]
source = commuted_calligraphy
relative_files = True
parallel = True
branch = True

[coverage:report]
show_missing = True
skip_covered = False
